apiVersion: v1
kind: Service
metadata:
  name: cloudvault-backend-service
spec:
  selector:
    app: cloudvault-backend
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080